"""
Dicionario de termos musicais Ingles -> Portugues Brasileiro
"""

MUSIC_TERMS = {
    # Conceitos Basicos
    "pitch": "altura",
    "Pitch": "Altura",
    "notation": "notacao",
    "Notation": "Notacao",
    "octave": "oitava",
    "Octave": "Oitava",
    "accidentals": "acidentes",
    "Accidentals": "Acidentes",
    "accidental": "acidente",
    "Accidental": "Acidente",
    "enharmonic": "enarmonico",
    "Enharmonic": "Enarmonico",
    "note": "nota",
    "Note": "Nota",
    "notes": "notas",
    "Notes": "Notas",

    # Notas musicais
    "C": "Do",
    "D": "Re",
    "E": "Mi",
    "F": "Fa",
    "G": "Sol",
    "A": "La",
    "B": "Si",

    # Acidentes
    "sharp": "sustenido",
    "Sharp": "Sustenido",
    "flat": "bemol",
    "Flat": "Bemol",
    "natural": "bequadro",
    "Natural": "Bequadro",
    "double sharp": "dobrado sustenido",
    "Double Sharp": "Dobrado Sustenido",
    "double flat": "dobrado bemol",
    "Double Flat": "Dobrado Bemol",

    # Escalas
    "scale": "escala",
    "Scale": "Escala",
    "scales": "escalas",
    "Scales": "Escalas",
    "major": "maior",
    "Major": "Maior",
    "minor": "menor",
    "Minor": "Menor",
    "natural minor": "menor natural",
    "Natural Minor": "Menor Natural",
    "harmonic minor": "menor harmonica",
    "Harmonic Minor": "Menor Harmonica",
    "melodic minor": "menor melodica",
    "Melodic Minor": "Menor Melodica",
    "chromatic": "cromatica",
    "Chromatic": "Cromatica",
    "whole tone": "tons inteiros",
    "Whole Tone": "Tons Inteiros",
    "pentatonic": "pentatonica",
    "Pentatonic": "Pentatonica",

    # Intervalos
    "half step": "semitom",
    "Half Step": "Semitom",
    "half steps": "semitons",
    "Half Steps": "Semitons",
    "whole step": "tom",
    "Whole Step": "Tom",
    "whole steps": "tons",
    "Whole Steps": "Tons",
    "interval": "intervalo",
    "Interval": "Intervalo",
    "intervals": "intervalos",
    "Intervals": "Intervalos",
    "unison": "unissono",
    "Unison": "Unissono",
    "second": "segunda",
    "Second": "Segunda",
    "third": "terca",
    "Third": "Terca",
    "fourth": "quarta",
    "Fourth": "Quarta",
    "fifth": "quinta",
    "Fifth": "Quinta",
    "sixth": "sexta",
    "Sixth": "Sexta",
    "seventh": "setima",
    "Seventh": "Setima",
    "octave": "oitava",
    "Octave": "Oitava",
    "perfect": "justa",
    "Perfect": "Justa",
    "augmented": "aumentada",
    "Augmented": "Aumentada",
    "diminished": "diminuta",
    "Diminished": "Diminuta",
    "inversion": "inversao",
    "Inversion": "Inversao",

    # Acordes
    "chord": "acorde",
    "Chord": "Acorde",
    "chords": "acordes",
    "Chords": "Acordes",
    "triad": "triade",
    "Triad": "Triade",
    "triads": "triades",
    "Triads": "Triades",
    "seventh chord": "acorde de setima",
    "Seventh Chord": "Acorde de Setima",
    "seventh chords": "acordes de setima",
    "Seventh Chords": "Acordes de Setima",
    "root": "fundamental",
    "Root": "Fundamental",
    "root position": "posicao fundamental",
    "Root Position": "Posicao Fundamental",
    "first inversion": "primeira inversao",
    "First Inversion": "Primeira Inversao",
    "second inversion": "segunda inversao",
    "Second Inversion": "Segunda Inversao",
    "third inversion": "terceira inversao",
    "Third Inversion": "Terceira Inversao",
    "sus chord": "acorde sus",
    "Sus Chord": "Acorde Sus",
    "suspended": "suspensa",
    "Suspended": "Suspensa",
    "power chord": "power chord",
    "Power Chord": "Power Chord",

    # Funcoes harmonicas
    "tonic": "tonica",
    "Tonic": "Tonica",
    "dominant": "dominante",
    "Dominant": "Dominante",
    "subdominant": "subdominante",
    "Subdominant": "Subdominante",
    "supertonic": "supertonica",
    "Supertonic": "Supertonica",
    "mediant": "mediante",
    "Mediant": "Mediante",
    "submediant": "submediante",
    "Submediant": "Submediante",
    "leading tone": "sensivel",
    "Leading Tone": "Sensivel",
    "subtonic": "subtonica",
    "Subtonic": "Subtonica",
    "scale degree": "grau da escala",
    "Scale Degree": "Grau da Escala",
    "scale degrees": "graus da escala",
    "Scale Degrees": "Graus da Escala",

    # Cadencias
    "cadence": "cadencia",
    "Cadence": "Cadencia",
    "cadences": "cadencias",
    "Cadences": "Cadencias",
    "authentic": "autentica",
    "Authentic": "Autentica",
    "perfect authentic cadence": "cadencia autentica perfeita",
    "Perfect Authentic Cadence": "Cadencia Autentica Perfeita",
    "imperfect authentic cadence": "cadencia autentica imperfeita",
    "Imperfect Authentic Cadence": "Cadencia Autentica Imperfeita",
    "half cadence": "semicadencia",
    "Half Cadence": "Semicadencia",
    "plagal cadence": "cadencia plagal",
    "Plagal Cadence": "Cadencia Plagal",
    "deceptive cadence": "cadencia de engano",
    "Deceptive Cadence": "Cadencia de Engano",

    # Ritmo
    "rhythm": "ritmo",
    "Rhythm": "Ritmo",
    "beat": "tempo",
    "Beat": "Tempo",
    "beats": "tempos",
    "Beats": "Tempos",
    "meter": "compasso",
    "Meter": "Compasso",
    "time signature": "formula de compasso",
    "Time Signature": "Formula de Compasso",
    "measure": "compasso",
    "Measure": "Compasso",
    "measures": "compassos",
    "Measures": "Compassos",
    "bar": "barra",
    "Bar": "Barra",
    "bars": "barras",
    "Bars": "Barras",
    "barline": "barra de compasso",
    "Barline": "Barra de Compasso",
    "downbeat": "tempo forte",
    "Downbeat": "Tempo Forte",
    "upbeat": "anacruse",
    "Upbeat": "Anacruse",
    "syncopation": "sincope",
    "Syncopation": "Sincope",
    "tuplet": "quialtera",
    "Tuplet": "Quialtera",
    "tuplets": "quialteras",
    "Tuplets": "Quialteras",
    "triplet": "tercina",
    "Triplet": "Tercina",
    "triplets": "tercinas",
    "Triplets": "Tercinas",

    # Figuras ritmicas
    "whole note": "semibreve",
    "Whole Note": "Semibreve",
    "half note": "minima",
    "Half Note": "Minima",
    "quarter note": "seminima",
    "Quarter Note": "Seminima",
    "eighth note": "colcheia",
    "Eighth Note": "Colcheia",
    "sixteenth note": "semicolcheia",
    "Sixteenth Note": "Semicolcheia",
    "thirty-second note": "fusa",
    "Thirty-second Note": "Fusa",
    "sixty-fourth note": "semifusa",
    "Sixty-fourth Note": "Semifusa",
    "whole rest": "pausa de semibreve",
    "Whole Rest": "Pausa de Semibreve",
    "half rest": "pausa de minima",
    "Half Rest": "Pausa de Minima",
    "quarter rest": "pausa de seminima",
    "Quarter Rest": "Pausa de Seminima",
    "eighth rest": "pausa de colcheia",
    "Eighth Rest": "Pausa de Colcheia",
    "sixteenth rest": "pausa de semicolcheia",
    "Sixteenth Rest": "Pausa de Semicolcheia",
    "dot": "ponto",
    "Dot": "Ponto",
    "dotted": "pontuado",
    "Dotted": "Pontuado",
    "tie": "ligadura",
    "Tie": "Ligadura",
    "ties": "ligaduras",
    "Ties": "Ligaduras",

    # Claves
    "clef": "clave",
    "Clef": "Clave",
    "clefs": "claves",
    "Clefs": "Claves",
    "treble clef": "clave de sol",
    "Treble Clef": "Clave de Sol",
    "bass clef": "clave de fa",
    "Bass Clef": "Clave de Fa",
    "alto clef": "clave de do",
    "Alto Clef": "Clave de Do",
    "tenor clef": "clave de do na quarta linha",
    "Tenor Clef": "Clave de Do na Quarta Linha",
    "grand staff": "pauta dupla",
    "Grand Staff": "Pauta Dupla",
    "staff": "pauta",
    "Staff": "Pauta",
    "staves": "pautas",
    "Staves": "Pautas",
    "ledger line": "linha suplementar",
    "Ledger Line": "Linha Suplementar",
    "ledger lines": "linhas suplementares",
    "Ledger Lines": "Linhas Suplementares",

    # Armadura de clave
    "key signature": "armadura de clave",
    "Key Signature": "Armadura de Clave",
    "key signatures": "armaduras de clave",
    "Key Signatures": "Armaduras de Clave",
    "key": "tonalidade",
    "Key": "Tonalidade",
    "keys": "tonalidades",
    "Keys": "Tonalidades",

    # Progressoes harmonicas
    "harmonic progression": "progressao harmonica",
    "Harmonic Progression": "Progressao Harmonica",
    "chord progression": "progressao de acordes",
    "Chord Progression": "Progressao de Acordes",
    "circle of fifths": "ciclo de quintas",
    "Circle of Fifths": "Ciclo de Quintas",
    "harmonic rhythm": "ritmo harmonico",
    "Harmonic Rhythm": "Ritmo Harmonico",
    "harmonic function": "funcao harmonica",
    "Harmonic Function": "Funcao Harmonica",

    # Notas nao-acordais
    "non-chord tone": "nota estranha ao acorde",
    "Non-Chord Tone": "Nota Estranha ao Acorde",
    "non-chord tones": "notas estranhas ao acorde",
    "Non-Chord Tones": "Notas Estranhas ao Acorde",
    "passing tone": "nota de passagem",
    "Passing Tone": "Nota de Passagem",
    "passing tones": "notas de passagem",
    "Passing Tones": "Notas de Passagem",
    "neighbor tone": "bordadura",
    "Neighbor Tone": "Bordadura",
    "neighbor tones": "bordaduras",
    "Neighbor Tones": "Bordaduras",
    "appoggiatura": "apojatura",
    "Appoggiatura": "Apojatura",
    "escape tone": "escapada",
    "Escape Tone": "Escapada",
    "anticipation": "antecipacao",
    "Anticipation": "Antecipacao",
    "suspension": "suspensao",
    "Suspension": "Suspensao",
    "suspensions": "suspensoes",
    "Suspensions": "Suspensoes",
    "retardation": "retardo",
    "Retardation": "Retardo",
    "pedal point": "pedal",
    "Pedal Point": "Pedal",
    "pedal tone": "nota pedal",
    "Pedal Tone": "Nota Pedal",

    # Analise melodica
    "melody": "melodia",
    "Melody": "Melodia",
    "melodies": "melodias",
    "Melodies": "Melodias",
    "melodic": "melodico",
    "Melodic": "Melodico",
    "motive": "motivo",
    "Motive": "Motivo",
    "motif": "motivo",
    "Motif": "Motivo",
    "phrase": "frase",
    "Phrase": "Frase",
    "phrases": "frases",
    "Phrases": "Frases",
    "period": "periodo",
    "Period": "Periodo",
    "sentence": "sentenca",
    "Sentence": "Sentenca",
    "antecedent": "antecedente",
    "Antecedent": "Antecedente",
    "consequent": "consequente",
    "Consequent": "Consequente",
    "fragment": "fragmento",
    "Fragment": "Fragmento",
    "subphrase": "subfrase",
    "Subphrase": "Subfrase",
    "elision": "elisao",
    "Elision": "Elisao",

    # Forma musical
    "form": "forma",
    "Form": "Forma",
    "binary form": "forma binaria",
    "Binary Form": "Forma Binaria",
    "ternary form": "forma ternaria",
    "Ternary Form": "Forma Ternaria",
    "verse": "verso",
    "Verse": "Verso",
    "chorus": "refrão",
    "Chorus": "Refrão",
    "bridge": "ponte",
    "Bridge": "Ponte",
    "intro": "introducao",
    "Intro": "Introducao",
    "introduction": "introducao",
    "Introduction": "Introducao",
    "outro": "coda",
    "Outro": "Coda",
    "coda": "coda",
    "Coda": "Coda",
    "sonata": "sonata",
    "Sonata": "Sonata",
    "rondo": "rondo",
    "Rondo": "Rondo",
    "exposition": "exposicao",
    "Exposition": "Exposicao",
    "development": "desenvolvimento",
    "Development": "Desenvolvimento",
    "recapitulation": "recapitulacao",
    "Recapitulation": "Recapitulacao",

    # Textura
    "texture": "textura",
    "Texture": "Textura",
    "monophonic": "monofonica",
    "Monophonic": "Monofonica",
    "homophonic": "homofonica",
    "Homophonic": "Homofonica",
    "polyphonic": "polifonica",
    "Polyphonic": "Polifonica",
    "heterophonic": "heterofonica",
    "Heterophonic": "Heterofonica",
    "accompaniment": "acompanhamento",
    "Accompaniment": "Acompanhamento",
    "chorale": "coral",
    "Chorale": "Coral",
    "arpeggiated": "arpejado",
    "Arpeggiated": "Arpejado",
    "block chord": "acorde em bloco",
    "Block Chord": "Acorde em Bloco",

    # Baixo cifrado
    "figured bass": "baixo cifrado",
    "Figured Bass": "Baixo Cifrado",
    "six-four chord": "acorde de quarta e sexta",
    "Six-Four Chord": "Acorde de Quarta e Sexta",
    "cadential six-four": "quarta e sexta cadencial",
    "Cadential Six-Four": "Quarta e Sexta Cadencial",

    # Dominantes secundarias
    "secondary dominant": "dominante secundaria",
    "Secondary Dominant": "Dominante Secundaria",
    "secondary dominants": "dominantes secundarias",
    "Secondary Dominants": "Dominantes Secundarias",
    "tonicization": "tonicizacao",
    "Tonicization": "Tonicizacao",
    "secondary diminished": "diminuta secundaria",
    "Secondary Diminished": "Diminuta Secundaria",

    # Mistura de modos
    "mode mixture": "mistura de modos",
    "Mode Mixture": "Mistura de Modos",
    "borrowed chord": "acorde emprestado",
    "Borrowed Chord": "Acorde Emprestado",
    "borrowed chords": "acordes emprestados",
    "Borrowed Chords": "Acordes Emprestados",
    "Picardy third": "terca de picardia",
    "Picardy Third": "Terca de Picardia",

    # Acordes especiais
    "Neapolitan": "Napolitano",
    "Neapolitan chord": "acorde napolitano",
    "Neapolitan Chord": "Acorde Napolitano",
    "augmented sixth": "sexta aumentada",
    "Augmented Sixth": "Sexta Aumentada",
    "Italian sixth": "sexta italiana",
    "Italian Sixth": "Sexta Italiana",
    "French sixth": "sexta francesa",
    "French Sixth": "Sexta Francesa",
    "German sixth": "sexta alema",
    "German Sixth": "Sexta Alema",

    # Modulacao
    "modulation": "modulacao",
    "Modulation": "Modulacao",
    "pivot chord": "acorde pivo",
    "Pivot Chord": "Acorde Pivo",
    "common chord": "acorde comum",
    "Common Chord": "Acorde Comum",
    "direct modulation": "modulacao direta",
    "Direct Modulation": "Modulacao Direta",
    "enharmonic modulation": "modulacao enarmonica",
    "Enharmonic Modulation": "Modulacao Enarmonica",

    # Conducao de vozes
    "voice leading": "conducao de vozes",
    "Voice Leading": "Conducao de Vozes",
    "parallel motion": "movimento paralelo",
    "Parallel Motion": "Movimento Paralelo",
    "contrary motion": "movimento contrario",
    "Contrary Motion": "Movimento Contrario",
    "oblique motion": "movimento obliquo",
    "Oblique Motion": "Movimento Obliquo",
    "similar motion": "movimento direto",
    "Similar Motion": "Movimento Direto",
    "parallel fifths": "quintas paralelas",
    "Parallel Fifths": "Quintas Paralelas",
    "parallel octaves": "oitavas paralelas",
    "Parallel Octaves": "Oitavas Paralelas",
    "voice range": "extensao vocal",
    "Voice Range": "Extensao Vocal",
    "soprano": "soprano",
    "Soprano": "Soprano",
    "alto": "contralto",
    "Alto": "Contralto",
    "tenor": "tenor",
    "Tenor": "Tenor",
    "bass": "baixo",
    "Bass": "Baixo",
    "doubling": "dobragem",
    "Doubling": "Dobragem",

    # Contraponto
    "counterpoint": "contraponto",
    "Counterpoint": "Contraponto",
    "species counterpoint": "contraponto de especies",
    "Species Counterpoint": "Contraponto de Especies",
    "first species": "primeira especie",
    "First Species": "Primeira Especie",
    "second species": "segunda especie",
    "Second Species": "Segunda Especie",
    "third species": "terceira especie",
    "Third Species": "Terceira Especie",
    "fourth species": "quarta especie",
    "Fourth Species": "Quarta Especie",
    "fifth species": "quinta especie",
    "Fifth Species": "Quinta Especie",
    "cantus firmus": "cantus firmus",
    "Cantus Firmus": "Cantus Firmus",
    "fugue": "fuga",
    "Fugue": "Fuga",
    "invention": "invencao",
    "Invention": "Invencao",
    "subject": "sujeito",
    "Subject": "Sujeito",
    "answer": "resposta",
    "Answer": "Resposta",
    "countersubject": "contra-sujeito",
    "Countersubject": "Contra-sujeito",

    # Jazz
    "jazz": "jazz",
    "Jazz": "Jazz",
    "swing": "swing",
    "Swing": "Swing",
    "bebop": "bebop",
    "Bebop": "Bebop",
    "blues": "blues",
    "Blues": "Blues",
    "lead sheet": "cifra",
    "Lead Sheet": "Cifra",
    "chord voicing": "voicing de acorde",
    "Chord Voicing": "Voicing de Acorde",
    "chord voicings": "voicings de acordes",
    "Chord Voicings": "Voicings de Acordes",
    "altered chord": "acorde alterado",
    "Altered Chord": "Acorde Alterado",
    "extended chord": "acorde estendido",
    "Extended Chord": "Acorde Estendido",

    # Musica contemporanea
    "impressionism": "impressionismo",
    "Impressionism": "Impressionismo",
    "pandiatonicism": "pandiatonismo",
    "Pandiatonicism": "Pandiatonismo",
    "quintal harmony": "harmonia quartal",
    "Quintal Harmony": "Harmonia Quartal",
    "polychord": "poliacorde",
    "Polychord": "Poliacorde",
    "polychords": "poliacordes",
    "Polychords": "Poliacordes",
    "set theory": "teoria dos conjuntos",
    "Set Theory": "Teoria dos Conjuntos",
    "prime form": "forma prima",
    "Prime Form": "Forma Prima",
    "normal form": "forma normal",
    "Normal Form": "Forma Normal",
    "interval vector": "vetor intervalar",
    "Interval Vector": "Vetor Intervalar",
    "serialism": "serialismo",
    "Serialism": "Serialismo",
    "twelve-tone": "dodecafonico",
    "Twelve-Tone": "Dodecafonico",
    "tone row": "serie",
    "Tone Row": "Serie",
    "minimalism": "minimalismo",
    "Minimalism": "Minimalismo",
    "phase shifting": "defasagem",
    "Phase Shifting": "Defasagem",
    "additive process": "processo aditivo",
    "Additive Process": "Processo Aditivo",

    # Termos gerais
    "practice exercises": "exercicios praticos",
    "Practice Exercises": "Exercicios Praticos",
    "basic concepts": "conceitos basicos",
    "Basic Concepts": "Conceitos Basicos",
    "introduction": "introducao",
    "Introduction": "Introducao",
    "example": "exemplo",
    "Example": "Exemplo",
    "examples": "exemplos",
    "Examples": "Exemplos",
    "chapter": "capitulo",
    "Chapter": "Capitulo",
    "section": "secao",
    "Section": "Secao",
    "summary": "resumo",
    "Summary": "Resumo",
    "analysis": "analise",
    "Analysis": "Analise",
    "exercise": "exercicio",
    "Exercise": "Exercicio",
    "answer": "resposta",
    "Answer": "Resposta",
    "answers": "respostas",
    "Answers": "Respostas",

    # Titulos de capitulos
    "Music Theory for the 21st-Century Classroom": "Teoria Musical para a Sala de Aula do Seculo XXI",
    "Front Matter": "Preliminares",
    "Colophon": "Colofao",
    "Acknowledgements": "Agradecimentos",
    "Preface": "Prefacio",
    "Back Matter": "Material Complementar",
    "Index": "Indice",
    "Diatonic": "Diatonico",
    "diatonic": "diatonico",
    "Roman Numerals": "Numeros Romanos",
    "roman numerals": "numeros romanos",
}

# Mapeamento de titulos de paginas
PAGE_TITLES = {
    "MusicTheory.html": "TeoriaMusical.html",
    "frontmatter.html": "preliminares.html",
    "frontmatter-3.html": "preliminares-3.html",
    "frontmatter-4.html": "preliminares-4.html",
    "frontmatter-5.html": "preliminares-5.html",
    "BasicConcepts.html": "ConceitosBasicos.html",
    "Pitch.html": "Altura.html",
    "Notation.html": "Notacao.html",
    "OctaveRegisters.html": "RegistrosDeOitava.html",
    "Accidentals.html": "Acidentes.html",
    "EnharmonicNotes.html": "NotasEnarmonicas.html",
    "BasicConceptsPracticeExercises.html": "ConceitosBasicosExercicios.html",
}
